### ISSUE TITLE
Command to import users not working

### ISSUE THREAD

**Issue by simkoc** [timschubert/abgabesystem#4]
The command  `abgabesystem users -s <students.csv> -b <LDAP base domain> -p main` does not work as advertised:
1) it requires the `-c <course>` flag to be specified
2) it requires the subgroup students to exist (not listed in the documentation)
3) even with 1 & 2 taken into account it terminates with `WARNING:root:Failed to create user: simkoch`
(simkoch is the first user in the csv list)

I assume it is some permission issue. Under what permission settings does the abgabesystem have to run?

As a side note: the .csv exported from studip does not contain a "group" column so mentioning this in the documentation could be helpful though it is fairly easy to deduct from the error message and source code.

**Comment by simkoc** [comment]
Just realized that point (3) is a duplicate warning is, thus this can be disregarded (the error message could be improved though). The remaining points are only concerning documentation.

**Comment by timschubert** [comment]
There are two possible CSV files that can be exported from Stud.IP. The first does not contain any groups (as you mentioned). The second can be exported from the tab "Groups and Functions" and contains all information including the groups. This should be mentioned in the documentation.

Regarding your first issue: The `course` subcommand does create the student subgroup, but the documentation also allows to create the group using the Gitlab UI. In this case the subgroup would not be created. I will open a separate issue to address this problem, since creating the course needs Admin priviledges but creating the subgroup does not and this functionality should be separated out and be called by the CI or the `users` subcommand.
